syntax fix

diff --git a/roles/dataguard_precheck/templates/standby_precheck.sh.j2 b/roles/dataguard_precheck/templates/standby_precheck.sh.j2
--- a/roles/dataguard_precheck/templates/standby_precheck.sh.j2
+++ b/roles/dataguard_precheck/templates/standby_precheck.sh.j2
@@ -60,14 +60,27 @@ check_size() {
 
     if [[ "$grid_asm_flag" == "true" ]]; then
         # ASM Disk Group Available Space Check
-        available_space=$(sqlplus -s / as sysdba <<SQL | tee -a "$MASTER_LOG"
+sqlplus -s / as sysasm <<SQL | tee "$MASTER_LOG"
 SET HEADING OFF
 SET FEEDBACK OFF
 SET PAGESIZE 0
-SELECT ROUND(USABLE_FILE_MB / 1024, 2) FROM v\$asm_diskgroup WHERE name=UPPER($dg_name);
+SET LINESIZE 1000
+SET TRIMOUT ON
+SET TRIMSPOOL ON
+
+-- Precheck 1: Diskgroup existence
+SELECT 'available_space:' || ROUND(USABLE_FILE_MB / 1024, 2) FROM v\$asm_diskgroup WHERE name=UPPER($dg_name);
 EXIT;
 SQL
-)
+
+        SQL_STATUS=$?
+        if [[ "$SQL_STATUS" -ne 0 ]]; then
+            echo "ERROR: SQL execution failed!" | tee -a "$FAILURE_LOG"
+            exit 1
+        fi
+
+        # Extracting values using grep and awk
+        available_space=$(grep "available_space:" "$MASTER_LOG" | awk -F ':' '{print $2}')
 
         if [[ -z "$available_space" || ! [[ "$available_space" =~ ^[0-9]+(\.[0-9]+)?$ ]] ]]; then
             echo "Error: Failed to retrieve available space from ASM or SQL command failed." | tee -a "$FAILURE_LOG"
