syntax check

diff --git a/roles/standby_config/templates/standby_config.sh.j2 b/roles/standby_config/templates/standby_config.sh.j2
--- a/roles/standby_config/templates/standby_config.sh.j2
+++ b/roles/standby_config/templates/standby_config.sh.j2
@@ -113,59 +113,57 @@ EOF
 
 elif [[ "$WITH_BACKUP" == "false" ]]; then
 
-rman_listener_file="${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener/listener.ora"
-tnsnames_file="${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener/tnsnames.ora"
-tnsnames_dir="${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener"
-
-# Define port range
-START_PORT=1521
-END_PORT=1600
-
-# Find the first available port
-PORT=""
-typeset -i P=$START_PORT
-
-while [ $P -le $END_PORT ]; do
-    if ! netstat -an | awk '/LISTEN/ {print $4}' | grep -E ".*\.$P$" >/dev/null; then
-        PORT=$P
-        echo "Available port: $PORT" | tee -a "$MASTER_LOG"
-        break
-    fi
-    P=$((P + 1))  # Increment
-done
-
-# If no port was found, log the failure and exit
-if [[ -z "$PORT" ]]; then
-    echo "No available ports found in range 1521-1600" | tee -a "$FAILURE_LOG"
-    exit 1
-fi
-
-# Create  if it doesn't exist
-if [[ ! -d "${tnsnames_dir}" ]]; then
-    mkdir -p "${tnsnames_dir}"
-fi
-
-if [[ ! -f "$tnsnames_file" ]]; then
-    echo "tnsnames.ora not found. Creating new file..."
-    touch "$tnsnames_file"
-else 
-   cp "$tnsnames_file" "$tnsnames_file.bak"
-   echo "Using existing tnsnames.ora file..."
-fi
-
-# Ensure rman_listener_file exists
-if [ ! -f "$rman_listener_file" ]; then
-  echo "File $rman_listener_file does not exist. Creating it..."
-  touch "$rman_listener_file"
-fi
-
-# Insert a static entry for standby in the listener.ora file if not updated before
-if ! grep -q "${standby_unique_name}" "$rman_listener_file"; then
-  cp "$rman_listener_file" "${rman_listener_file}.bak"
-  echo "Updating $rman_listener_file..."
-
-  cat <<EOL >> "$rman_listener_file"
-
+  rman_listener_file="${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener/listener.ora"
+  tnsnames_file="${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener/tnsnames.ora"
+  tnsnames_dir="${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener"
+  
+  # Define port range
+  START_PORT=1521
+  END_PORT=1600
+  
+  # Find the first available port
+  PORT=""
+  typeset -i P=$START_PORT
+  
+  while [ $P -le $END_PORT ]; do
+      if ! netstat -an | awk '/LISTEN/ {print $4}' | grep -E ".*\.$P$" >/dev/null; then
+          PORT=$P
+          echo "Available port: $PORT" | tee -a "$MASTER_LOG"
+          break
+      fi
+      P=$((P + 1))  # Increment
+  done
+  
+  # If no port was found, log the failure and exit
+  if [[ -z "$PORT" ]]; then
+      echo "No available ports found in range 1521-1600" | tee -a "$FAILURE_LOG"
+      exit 1
+  fi
+  
+  # Create  if it doesn't exist
+  if [[ ! -d "${tnsnames_dir}" ]]; then
+      mkdir -p "${tnsnames_dir}"
+  fi
+  
+  if [[ ! -f "$tnsnames_file" ]]; then
+      echo "tnsnames.ora not found. Creating new file..."
+      touch "$tnsnames_file"
+  else 
+     cp "$tnsnames_file" "$tnsnames_file.bak"
+     echo "Using existing tnsnames.ora file..."
+  fi
+  
+  # Ensure rman_listener_file exists
+  if [ ! -f "$rman_listener_file" ]; then
+    echo "File $rman_listener_file does not exist. Creating it..."
+    touch "$rman_listener_file"
+  fi
+  
+  # Insert a static entry for standby in the listener.ora file if not updated before
+  if ! grep -q "${standby_unique_name}" "$rman_listener_file"; then
+    cp "$rman_listener_file" "${rman_listener_file}.bak"
+    echo "Updating $rman_listener_file..."  
+    cat <<EOL >> "$rman_listener_file"  
 # listener.ora Network Configuration File: ${ORACLE_HOME}/network/admin/${standby_unique_name}_rman_listener/listener.ora
 # Generated by Dataguard Ansible playbook
 
@@ -185,12 +183,13 @@ SID_LIST_RMAN_LISTENER =
     )
    )
 EOL
-  echo "RMAN listener entry added successfully."
-else
-  echo "Entry for ${standby_unique_name} already exists. Skipping update."
-fi
-  export TNS_ADMIN="${tnsnames_dir}"
-  $ORACLE_HOME/bin/lsnrctl start rman_listener >> "$MASTER_LOG"
+    echo "RMAN listener entry added successfully."
+  else
+    echo "Entry for ${standby_unique_name} already exists. Skipping update."
+  fi
+   export TNS_ADMIN="${tnsnames_dir}"
+   echo $TNS_ADMIN >> $MASTER_LOG
+   $ORACLE_HOME/bin/lsnrctl start rman_listener >> "$MASTER_LOG"
   if [ $? -eq 0 ]; then
     echo "Listener start successful" | tee -a "$MASTER_LOG"
   else
@@ -239,26 +238,26 @@ ${primary_unique_name}=
   )
 )"
 
-# Check if the entries already exist in tnsnames.ora before appending
-if ! grep -q "$standby_unique_name=" "$tnsnames_file"; then    
-  echo "$STDBY_ENTRY" >> "$tnsnames_file"
-  echo "TNS alias added for standby database tnsnames.ora."
-else
-  echo "Entry already exists. Skipping update."
-fi
-
-if ! grep -q "$primary_unique_name=" "$tnsnames_file"; then    
-  echo "$PRIMY_ENTRY" >> "$tnsnames_file"
-  echo "TNS alias added for primary database tnsnames.ora."
-else
-  echo "Entry already exists. Skipping update."
-fi
-
-  # Create an initialization parameter with only DB_NAME
-  echo "DB_NAME=${primary_db_name}" > "$PFILE"
-  chown {{ db_oracle_user }}:{{ db_oinstall_group }} "$PFILE"
-  chmod 755 "$PFILE"
-
+  # Check if  the entries already exist in tnsnames.ora before appending
+  if ! grep -q "$standby_unique_name=" "$tnsnames_file"; then    
+    echo "$STDBY_ENTRY" >> "$tnsnames_file"
+    echo "TNS alias added for standby database tnsnames.ora."
+  else
+    echo "Entry already exists. Skipping update."
+  fi
+  
+  if ! grep -q "$primary_unique_name=" "$tnsnames_file"; then    
+    echo "$PRIMY_ENTRY" >> "$tnsnames_file"
+    echo "TNS alias added for primary database tnsnames.ora."
+  else
+    echo "Entry already exists. Skipping update."
+  fi
+  
+    # Create an initialization parameter with only DB_NAME
+    echo "DB_NAME=${primary_db_name}" > "$PFILE"
+    chown {{ db_oracle_user }}:{{ db_oinstall_group }} "$PFILE"
+    chmod 755 "$PFILE"
+  
 else
   echo "ERROR: Invalid value for 'with_backup'. Please provide 'true' or 'false'." | tee -a "$FAILURE_LOG"
   exit 1
