register in rman local listser running on DB owner home , without touching listener file

diff --git a/roles/standby_config/templates/standby_config.sh.j2 b/roles/standby_config/templates/standby_config.sh.j2
--- a/roles/standby_config/templates/standby_config.sh.j2
+++ b/roles/standby_config/templates/standby_config.sh.j2
@@ -14,7 +14,8 @@ standby_unique_name="{{ databases[database_name].db_unique_name }}"
 db_recovery_file_dest="{{ databases[database_name].db_recovery_file_dest }}"
 db_recovery_file_dest_size="{{ databases[database_name].db_recovery_file_dest_size }}"
 db_create_online_log_dest_1="{{ databases[database_name].online_log_dest1 }}"
-tnsnames_file="$ORACLE_HOME/network/admin/tnsnames.ora"
+#tnsnames_file="$ORACLE_HOME/network/admin/tnsnames.ora"
+tnsnames_file="${ORACLE_HOME}/network/admin/{{ standby_unique_name }}_rman_listener/tnsnames.ora"
 MASTER_LOG="{{ done_dir }}/standby_tns.log"
 FAILURE_LOG="{{ done_dir }}/standby_tns_fail.log"
 
@@ -24,7 +25,8 @@ log_file_name_convert="'${primary_diskgroup}/${primary_unique_name}','${standby_
 db_file_name_convert="'${primary_diskgroup}/${primary_unique_name}','${standby_diskgroup}/${standby_unique_name}'"
 audit_file_dest="'${oracle_db_base}/admin/${standby_unique_name}/adump'"
 local_listener="'(ADDRESS=(PROTOCOL=TCP)(HOST={{ standby_host }})(PORT={{ databases[database_name].db_port }}))'"
-listener_file=${GRID_HOME}/network/admin/listener.ora
+#listener_file=${GRID_HOME}/network/admin/listener.ora
+rman_listener_file="${ORACLE_HOME}/network/admin/{{ standby_unique_name }}_rman_listener/rman_listener.ora"
 db_create_file_dest="'${standby_diskgroup}'"
 db_recovery_file_dest="'${db_recovery_file_dest}'"
 db_create_online_log_dest_1="'${db_create_online_log_dest_1}'"
@@ -111,14 +113,24 @@ EOF
   cat "$PFILE"
 
 elif [[ "$WITH_BACKUP" == "false" ]]; then
+
+export TNS_ADMIN=${ORACLE_HOME}/network/admin/{{ standby_unique_name }}_rman_listener/rman_listener.ora
   # Insert a static entry for standby in the listener.ora file if not updated before
-  if ! grep -q "${standby_unique_name}" "$listener_file"; then
-    cp "$listener_file" "${listener_file}.bak"
-    echo "Updating listener.ora..."
-    cat <<EOL >> "$listener_file"
+  if ! grep -q "${standby_unique_name}" "$rman_listener_file"; then
+    cp "$rman_listener_file" "${rman_listener_file}.bak"
+    echo "Updating rman_listener_file.ora..."
+    cat <<EOL >> "$rman_listener_file"
+# listener.ora Network Configuration File: ${ORACLE_HOME}/network/admin/{{ standby_unique_name }}_rman_listener/rman_listener.ora
+# Generated by Dataguard ansible play
 
+RMAN_LISTENER =
+  (DESCRIPTION_LIST =
+    (DESCRIPTION =
+      (ADDRESS = (PROTOCOL = TCP)(HOST = {{ standby_host }})(PORT = 1523))
+    )
+  )
 
-SID_LIST_LISTENER =
+SID_LIST_RMAN_LISTENER =
   (SID_LIST =
     (SID_DESC =
      (GLOBAL_DBNAME = ${standby_unique_name})
@@ -126,19 +138,18 @@ SID_LIST_LISTENER =
      (SID_NAME = ${ORACLE_SID})
     )
    )
-
 EOL
   fi
 
-  echo "$1" | su - {{ grid_user }} -c "$GRID_HOME/bin/lsnrctl reload" >> "$MASTER_LOG"
+  $ORACLE_HOME/bin/lsnrctl start rman_listener >> "$MASTER_LOG"
   if [ $? -eq 0 ]; then
-    echo "Listener reload successful" | tee -a "$MASTER_LOG"
+    echo "Listener start successful" | tee -a "$MASTER_LOG"
   else
-    echo "Listener reload failed" | tee -a "$FAILURE_LOG"
+    echo "Listener start failed" | tee -a "$FAILURE_LOG"
     exit 1
   fi
 
-  echo "$1" | su - {{ grid_user }} -c "$GRID_HOME/bin/lsnrctl status" >> "$MASTER_LOG"
+  $ORACLE_HOME/bin/lsnrctl status >> "$MASTER_LOG"
   if [ $? -eq 0 ]; then
     echo "Listener is running successfully" | tee -a "$MASTER_LOG"
   else
